"""create protuct and category table fixed

Revision ID: dd138d7b3e09
Revises: 34351a3c7dd8
Create Date: 2026-09-14 20:23:36.216010

"""

from typing import Sequence, Union

from alembic import op  # noqa
import sqlalchemy as sa  # noqa


# revision identifiers, used by Alembic.
revision: str = "dd138d7b3e09"
down_revision: Union[str, Sequence[str], None] = "34351a3c7dd8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
